---
- name: Deploy to backend instance
  hosts: backservers
  become: yes

  vars:   
    name_docker_repo: backend

  tasks:
  - name: login to aws ecr
    shell: /usr/local/bin/aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin 059556936706.dkr.ecr.us-east-2.amazonaws.com/{{ name_docker_repo }}
  
  - name: Get infos on container
    docker_container_info:
      name: app
    register: info_container
  
  - name: pull docker image from ecr
    shell: docker pull 059556936706.dkr.ecr.us-east-2.amazonaws.com/{{ name_docker_repo }}:"{{ VERSION }}"

  - name: install docker-py for ansible modules
    pip:
      name: python

  - name: run docker container with python app
    docker_container:
      name: app
      image: 059556936706.dkr.ecr.us-east-2.amazonaws.com/{{ name_docker_repo }}:{{ VERSION }}
      state: started
      published_ports:
      - "80:80"
      log_driver: json-file
      restart_policy: always
      network_mode: bridge
      tty: true
      detach: true
    when: info_container.exists == "False"

  - name: Wait for the Application (80) port to become open.
    wait_for:
      host: 127.0.0.1
      port: "{{ item }}"
      timeout: 420
      delay: 15
    with_items:
    - 80
